Repository PAWCUT/PAWCUT-iOS, pull requests merged in 2025-09, with the labels that each got.

#172 fix: 촬영대기 화면의 아이콘 네이밍 변경
  PawCut/PawCut/Resources/Assets.xcassets/ic_camera_sound.imageset/Contents.json
  PawCut/PawCut/Resources/Assets.xcassets/ic_camera_sound.imageset/Pawcut_Sound.png
  PawCut/PawCut/Resources/Assets.xcassets/ic_tip_arrow.imageset/Contents.json
  PawCut/PawCut/Resources/Assets.xcassets/ic_tip_arrow.imageset/tip_arrow.svg
  PawCut/PawCut/Resources/Assets.xcassets/ic_tip_camera.imageset/Contents.json
  PawCut/PawCut/Resources/Assets.xcassets/ic_tip_camera.imageset/tip_camera.svg
  PawCut/PawCut/Resources/Assets.xcassets/ic_tip_clock.imageset/Contents.json
  PawCut/PawCut/Resources/Assets.xcassets/ic_tip_clock.imageset/tip_clock.svg
  PawCut/PawCut/Resources/Assets.xcassets/ic_tip_hand.imageset/Contents.json
  PawCut/PawCut/Resources/Assets.xcassets/ic_tip_hand.imageset/tip_hand.svg
  PawCut/PawCut/Resources/Assets.xcassets/ic_tip_picture.imageset/Contents.json
  PawCut/PawCut/Resources/Assets.xcassets/ic_tip_picture.imageset/tip_picture.svg
  PawCut/PawCut/Sources/Views/PawcutCamera/PawcutTipView.swift
Labels: 🐛 Bug

#174 refactor: 네비게이션 관련 수정
  PawCut/PawCut/Sources/DesignSystem/Component/NavigationBar/PawBackButtonNavigationBar.swift
  PawCut/PawCut/Sources/Views/Archive/PhotoDetailsView.swift
  PawCut/PawCut/Sources/Views/PawcutCamera/PawcutCameraView.swift
  PawCut/PawCut/Sources/Views/PawcutCamera/PawcutTipView.swift
  PawCut/PawCut/Sources/Views/PawcutFrame/PawcutFrameView.swift
  PawCut/PawCut/Sources/Views/PawcutSelect/PawcutSelectionView.swift
Labels: 🛠️ Refactor

#187 dependency: Google Analytics 추가
  PawCut/PawCut.xcodeproj/project.pbxproj
  PawCut/PawCut.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PawCut/PawCut/GoogleService-Info.plist
  PawCut/PawCut/Sources/Application/PawCutApp.swift
Labels: ➕ Dependency

#199 [Refactor] PawcutCameraView 리펙토링
  PawCut/PawCut/Sources/Views/PawcutCamera/PawcutCameraView.swift
  PawCut/PawCut/Sources/Views/PawcutCamera/SubViews/PawcutCameraBottomSubView.swift
  PawCut/PawCut/Sources/Views/PawcutCamera/SubViews/PawcutCameraTopSubView.swift
Labels: 🛠️ Refactor, 🧑🏻‍🚒 Kwangro

#189 [Refactor] ArchiveView 관련 코드 리팩토링
  PawCut/PawCut/Sources/ViewModels/Archive/ArchiveViewModel.swift
  PawCut/PawCut/Sources/Views/Archive/ArchiveView.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/ArchiveCalendarView.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/ArchiveGridView.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/Calendar/ArchiveCalendarView.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/Empty/ArchiveEmptyView.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/Empty/Components/ExplainContents.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/Grid/ArchiveGridView.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/Grid/Components/PhotoDateOverlay.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/Grid/Components/PhotoGridCell.swift
Labels: 🛠️ Refactor, 🦹🏼‍♀️ Taeni

#190 [Refactor] PhotoDetailsView 관련 코드 리팩토링
  PawCut/PawCut/Sources/ViewModels/Archive/ArchiveViewModel.swift
  PawCut/PawCut/Sources/ViewModels/Archive/PhotoDetailsViewModel.swift
  PawCut/PawCut/Sources/Views/Archive/PhotoDetailsView.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/Details/Components/BottomControlButton.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/Details/Components/ThumbnailStripCell.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/Details/PhotoDetailsBottomControlView.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/Details/PhotoDetailsBottomControls.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/Details/PhotoDetailsHeaderTitle.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/Details/PhotoDetailsHeaderView.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/Details/PhotoDetailsImageGalleryView.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/Details/PhotoDetailsThumbnailStripView.swift
  PawCut/PawCut/Sources/Views/Archive/SubViews/Grid/ArchivePhotoDateOverlay.swift
Labels: 🛠️ Refactor, 🦹🏼‍♀️ Taeni
